name: cjson-fuzz-tester
on:
  pull_request:
    types: [opened, reopened]
    branches:
    - 'main'
  push:
    branches:
      - 'main'
jobs:
  build-docker-image:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run docker builder
      run: |
         chmod +x build.sh
         ./build.sh
      shell: bash
    - name: Exporting built docker image
      run: docker image save cjson-docker-image:latest -o cjson-docker-image.tar
    - name: Upload built docker image
      uses: actions/upload-artifact@v3
      with:
        name: cjson-docker-image
        path: cjson-docker-image.tar
      
  run-fuzz-tests:
    name: Run fuzz tests in docker
    runs-on: ubuntu-latest
    needs: build-docker-image
    steps:
    - uses: actions/checkout@v3
    - name: Download built docker image
      uses: actions/download-artifact@v2
      with:
        name: cjson-docker-image
        path: .
    - name: Load Docker image
      run: |
        docker load --input cjson-docker-image.tar
        docker image ls -a
    - name: Execute docker image
      run: |
         chmod +x run.sh
         ./run.sh
      shell: bash
